### ISSUE TITLE
Activate update not from ZF Tool but from the application itself

### ISSUE THREAD

**Issue by sirshurf** [akrabat/AkrabatZF#10]
Is there a way to activate the upgrade script from the ZF applicaiton and not thrue the ZF Tool Provider?

**Comment by akrabat** [comment]
Sure. Just instantiate an Akrabat_Db_Schema_Manager and start from there.

**Comment by sirshurf** [comment]
Testes, Done.... But is there a way to make versioning for a specific lets say Module?

**Comment by akrabat** [comment]
Not as-is. Akrabat_Db_Schema_Manager provides for versioning the database schema as a whole.

**Comment by sirshurf** [comment]
Ok, thanks I will improve it to work with modules :)
